# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-09 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('synopsis', models.TextField()),
                ('poster', models.ImageField(upload_to='posters')),
                ('director', models.CharField(max_length=140)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=140)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
